### ISSUE TITLE
[FR] merge multiple overlapping control points

### ISSUE THREAD

**Issue by VanessaE** [Lichtso/curve_cad#5]
At present, the "merge ends" in this plugin can merge overlapping end points in a way similar to merging vertexes in a mesh...  but it can only do one pair at a time.  Trying to do this on an entire set of curves just throws "invalid selection".

The plugin really should just pair-off all endpoints that it can from that which is selected (silently ignoring selected handles of course, so that one could just do the entire object at once)

**Comment by Lichtso** [comment]
Ok, I changed it so that the user selects the entire splines (e.g. by using select linked) and the tool then merges their ends based on their distance up to a maximum distance threshold parameter.

**Comment by VanessaE** [comment]
yay :smiley:

**Comment by VanessaE** [comment]
OOps, nope, still not working quite right.  Consider this model:

[Covid19 Face Shield Hole Punch V1.1.DXF.zip](https://github.com/Lichtso/curve_cad/files/4528658/Covid19.Face.Shield.Hole.Punch.V1.1.DXF.zip)

(original source: https://grabcad.com/library/covid19-face-shield-hole-punch-v1-1-1 )

Import this DXF, switch the curve to 2D, go into edit mode and convert the whole thing to bezier splines, select all control points, and merge.

The model... um, kinda turns to mush :smiley:, or it'll throw this error (I'm not sure why the behavior varies):

![image](https://user-images.githubusercontent.com/1733537/80209415-0d54ba80-8600-11ea-98aa-0faa03e491a9.png)

**Comment by Lichtso** [comment]
I think I fixed the bugs, as I can now import your model and merge everything correctly.

Three more tips, before merging the control points:
- Go into the data properties of the curve and select Shape '2D', as well as, Fill Mode 'Both'. That way you can easily tell if everything worked afterwards.
- Increase Geometry Extrude to add some depth to it.
- Select everything and set Spline Type 'Bezier' because there are some 'Poly' in the imported model.

**Comment by VanessaE** [comment]
Yep, now it looks right  (and, those tips are actually just what I was doing :smiley: )
